<a href="https://colab.research.google.com/github/9characters/RL_repo/blob/master/Frozen_Lake_Q_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install gym

In [0]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [0]:
#Make the environment
env = gym.make("FrozenLake-v0")
#All the envs are available at gym's website

In [0]:
# We will use the environment to sample state and actions, recieve rewards

Now Construct Q-Table and initialize all the Q-values to zero for each state action pair.

Number of rows in a table is equal to size of state space in the environment and the number of columns is equal to the number of action space.


In [0]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

In [7]:
#Build the Q-Table
q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
#Create and Initialize all the parameters needed to implement the Q-Learning algorithm
num_episodes = 10000
max_steps_per_episode = 100 #For termination, in a episode (receives zero point)

learning_rate = 0.1
discount_rate = 0.99 #gamma symbol

exploration_rate = 1 # epsilon value
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001 #Change with experiment

#The above parameters are to be trained and tuned

In [0]:
#Create a list to store the rewards in each episode
#To see how the game scores change everytime
rewards_all_episodes = []

# Q-learning algorithm
for episode in range(num_episodes):
    #Resetting to starting state for each episode
    state = env.reset()
    #To make sure the episode is finished
    done = False 
    rewards_current_episode = 0 #Keep track of reward in each episode

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1) #This is needed to whether know that our agent will eplore
                                                          # or exploit the environment
        if exploration_rate_threshold > exploration_rate: # If r>e in explanation, then exploit the environment
            action = np.argmax(q_table[state,:])     # And chooses the action with highest Q-value in the Q-table for the current state
        else:
            action = env.action_space.sample()      #Else explore the environment and sample an action randomly

        #After the action is chosen, we then take the action by calling env.step() function --> Execute the action
        new_state, reward, done, info = env.step(action) 
        #env.step() returns a tuple containig 4 items: 
        #1. new_state 2. reward for the action 3. whether or not action ended our episode 
        #4. diagnostic information of the environment which might be needed for debugging

        # Update Q-table for Q(s,a) as per the formula (weighted sum of old value and learned value)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
                                learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state #Current state is the new state
        rewards_current_episode += reward #add the cumulative reward

        #check if the episode is over or not
        if done == True: 
          break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
                       (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
                       
    #appends the rewards from the current episode               
    rewards_all_episodes.append(rewards_current_episode)

In [10]:
# After all episodes are completed, we calculate average reward per 1000 episodes
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.12600000000000008
2000 :  0.17100000000000012
3000 :  0.22200000000000017
4000 :  0.2850000000000002
5000 :  0.6450000000000005
6000 :  0.6560000000000005
7000 :  0.6910000000000005
8000 :  0.6800000000000005
9000 :  0.6910000000000005
10000 :  0.6810000000000005


Our agent played or 10,000 episodes. At each time-step, the agent received a reward of if it wins and 0 otherwise. We can interpret as at each 1000 episode, agent received a reward at the rate of 16% which changed to 70% win rate.

In [11]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[5.56263689e-01 5.06924634e-01 4.89980671e-01 5.09150956e-01]
 [2.80115432e-01 2.14635920e-01 1.58910064e-01 4.88620639e-01]
 [4.14903764e-01 2.07351467e-01 2.01000322e-01 2.07526265e-01]
 [1.09833192e-04 8.49251407e-02 5.62874826e-03 1.65729096e-05]
 [5.77640667e-01 3.77734042e-01 3.35903483e-01 4.19210209e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.36329130e-01 1.13947299e-01 1.58660790e-01 1.37044676e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.21518386e-01 4.90186305e-01 3.85899138e-01 6.12742299e-01]
 [5.08694063e-01 6.84070631e-01 4.09422910e-01 3.99965265e-01]
 [6.21732065e-01 4.00297560e-01 4.29698441e-01 2.90139994e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.06836845e-01 5.87768493e-01 7.69221430e-01 5.25923477e-01]
 [7.40424845e-01 9.10594917e-01 7.48525249e-01 7.15710202e-01]
 [0.00000000e+00 0.00000000e

In [13]:
for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render() # render the current state of the environment to the display so 
                     # that we can visualize the gamegrid and agent gale play
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)

        # If the episode is completed then we render the environment to see where the agent ended in the
        # environment by taking that action
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
